#if defined _cx_amx_macros
	#endinput
#endif
#define _cx_amx_macros


#define @CX_AMX@%0\32; @CX_AMX@
#define @CX_AMX_FROMPREFIX@%0\32; @CX_AMX_FROMPREFIX@

#define @CX_AMX@getfromprefix(%3.type%4= @CX_AMX_FROMPREFIX@
#define @CX_AMX@close(%0)%1; }
#define @CX_AMX@return<%5> returnFunc_%5

#define @CX_AMX_FROMPREFIX@public%2,%3.prefix%4=%6<%5>) amx_space @a_amx$%5$ amx_space @b_amx$%5$ amx_space @c_amx$%5$ amx_space @d_amx$%5$ amx_space @e_amx$%5$

#define @amx%0 @CX_AMX@